### ISSUE TITLE
Git Hooks and Actions

### ISSUE THREAD

**Issue by devlinjunker** [devlinjunker/template.github#5]
**IDEA:** `scripts/` directory:
```
- actions/ 
|-- (script files for actions to run successfully)
- deploy/
|-- (script files to run during deployment -- connecting to/installing/running on server)
- hooks/
|-- (script files to run with git hooks)
- release/
|-- (script files for building/creating releases)
```

Hooks:
- ~[ ] enforce workflow during local development~
    - ~run build/tests on commit~
    - need to know project build process
- [x] enforce branch names  to match labels (related to #8 )
    - https://itnext.io/using-git-hooks-to-enforce-branch-naming-policy-ffd81fa01e5e
    - type (e.g feature/bug/doc) followed by `/`
- [x] prevent commit to branch based on branch name
   - branches: `master`, `release-*`
- ~[ ] prevent tags being pushed from developer machine (pre-push hook to verify no new tags)~
     - only tag during release (in GitHub action)
     - tags are only pushed when explicitly told to
- [x] enforce commit messages? (Related to #4)
    - https://www.conventionalcommits.org/en/v1.0.0

Actions
- [x] Label Manager action (see #8)
   -  https://github.com/marketplace/actions/github-labeler
- [x] Clean up action strategy/naming
   - simple names (reflect when action occurs)
   - include branch name? action (merge/pr/issue/label/create)
- [x] Keep actions up to date?
   -  https://github.com/marketplace/actions/github-labeler#keep-up-to-date-with-github-dependabot
- [x] use PR Details to apply label
    - https://github.com/marketplace/actions/pr-branch-labeler
    - merge branch name `feature*` apply `subtask` label
         - for filtering out when searching 
    - merging branch name to apply label to PR (related to #8) 
         - e.g. doc/feat/feature/poc/example/perf/performance/qa/test/bug/build
    - [x] **Separate action for this** last commit `wip: ***` add `status:wip` label
- [x] Prevent `poc` or `status: wip` labeled commits or branches from being merged (Related #8)
- [x] prevent PR if status is failing on merge branch: https://github.com/cirruslabs/gh-submit-queue
- [x] Release Actions
   - Create Release Branch using semantic version in README -- see #4 (0.8-SNAPSHOT creates `release-0.8`) 
   - Increment version in README in `master` (0.8-SNAPSHOT -> 0.9-SNAPSHOT)
   - Github Release?
   - Git Tag
- [x] auto merge: https://github.com/palantir/bulldozer
   - https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#issue_comment
   - squash and merge (but why? see #17 )
   - on:
      - comment starting with`merge:`? Comment with `merge!`
      - all required checks passing (no wip last commit)
   - message:
      - always include PR number in merge commit message
      - PR title
        - [x] Enforce PR title in `verify-merge` action
           - match branch prefix
           - conventional commit style: `<prefix>(optional scope): <description>`
           - include PR number
       - ~use standarized merge commit message unless comment contains message after `merge`?~
- ~[ ] Greate Gihub Actions to build project on PR and commit to master~
   - this depends on on knowing the framework/build tools for the project though

**Comment by devlinjunker** [comment]
- [ ] review 
   - https://github.com/devlinjunker/template.hapi.rest/issues/9
   - https://github.com/devlinjunker/template.webpack.fend/issues/21
   - https://github.com/devlinjunker/template.hapi.rest/issues/5

**Comment by devlinjunker** [comment]
Add Design Documents for any scripts that we add, we can add sequence diagrams maybe? and explain where info is coming form?

**Comment by devlinjunker** [comment]
Created https://github.com/devlinjunker/test.github.actions
