### ISSUE TITLE
Add docs on how to update other Repos with new features from this repo

### ISSUE THREAD

**Issue by devlinjunker** [devlinjunker/template.github#9]
**Describe the change:**
Add document about how to reference this “template” repo in the forked repos and update the forked repos so any changes to this are included in those

- Can we add remote to other (existing) repos and merge from this develop to get all the stuff?

**Additional context/Links:**
- [x] Test this:
   - Add remote named “template”
   - upmerge local master from “template/master”
   - resolve conflicts

**TODO:**
- [x] Practice on repo that was template
- [x] Practice with repo that was not template
- [ ] Add notes/documentation on how to update to README

**Comment by devlinjunker** [comment]
current steps to update:
```
git checkout master;
git remote add template <repo_address>;
git checkout template/master ./;
git reset HEAD *;
<compare diff with `origin/master` to see updates>
```

**Comment by devlinjunker** [comment]
Reset changes after attempting to update:

```
git checkout <files that have changed>;
git clean -f -d;
```
